# Generated by Django 3.1.1 on 2020-09-14 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20200912_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Изображение')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('date_change', models.DateTimeField(auto_now=True, verbose_name='дата редактирования')),
                ('date_pub', models.DateTimeField(blank=True, null=True, verbose_name='дата публикации')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Черновик'), (1, 'ОПУБЛИКОВАН')], default=0, verbose_name='статус')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор статьи')),
            ],
            options={
                'verbose_name': 'Статью',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
