# Generated by Django 3.1.1 on 2020-09-30 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200914_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='img',
        ),
    ]
